apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: gcr.io/<PROJECT_ID>/todo-app:v1 # Replace <PROJECT_ID> with your GCP project ID.
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: todo-app-config
              key: APP_ENVIRONMENT
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: todo-app-config
              key: APP_DEBUG
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-app-secret
              key: DB_PASSWORD
